### ISSUE TITLE
The Pretrained weights for gan ('pretrained_dihe_gan.tar') does not exist

### ISSUE THREAD

**Issue by fadishaar84** [laitalaj/cvpce#1]
The file 'pretrained_dihe_gan.tar) does not exist in links you provided for weights, could you please share this weights file or guide me on how to initialize (generator, and discriminator) weights? Thank you.

**Comment by laitalaj** [comment]
Hey @fadishaar84 and @mrsahabu ! Sorry for the really late reply, I really ought to check if my GitHub mailing preferences are in order!

I guess it never occurred to me that someone would want to on one hand retrain this, but on the other hand not retrain the GAN 😅 anyways, I had the weights lying around, so no harm in sharing those. You can now find them in [the release](https://github.com/laitalaj/cvpce/releases/tag/v1.0.0)
